CREATE SCHEMA IF NOT EXISTS schema_a;
CREATE SCHEMA IF NOT EXISTS schema_b;
CREATE TABLE IF NOT EXISTS schema_a.table_a (id INT PRIMARY KEY, name VARCHAR(50));
CREATE TABLE IF NOT EXISTS schema_b.table_b (id INT PRIMARY KEY, label VARCHAR(50));
